"""add date_of_birth to users

Revision ID: 1c0ef9a8326e
Revises: e5a3f2e83213
Create Date: 2025-11-10 11:45:36.939897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0ef9a8326e'
down_revision: Union[str, Sequence[str], None] = 'e5a3f2e83213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Add column as nullable first so existing rows don't break
    op.add_column(
        "users",
        sa.Column("date_of_birth", sa.Text(), nullable=True),
    )

    # 2) Backfill existing rows with some placeholder or default value
    #    ⚠️ Choose something that makes sense for your project.
    #    For now we'll use '2000-01-01' as a dummy date.
    op.execute(
        "UPDATE users SET date_of_birth = '2000-01-01' WHERE date_of_birth IS NULL"
    )

    # 3) Now enforce NOT NULL
    op.alter_column(
        "users",
        "date_of_birth",
        existing_type=sa.Text(),
        nullable=False,
    )


def downgrade() -> None:
    op.drop_column("users", "date_of_birth")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'username')
    op.drop_table('login_history')
    # ### end Alembic commands ###
