[alembic]
script_location = migrations
<<<<<<< Updated upstream
sqlalchemy.url = postgresql+psycopg://smartstudy:changeme@localhost:5432/smartstudy

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

=======
sqlalchemy.url = %(DATABASE_URL)s

[loggers]
keys = root,sqlalchemy,alembic
[handlers]
keys = console
[formatters]
keys = generic
[logger_root]
level = WARN
handlers = console
>>>>>>> Stashed changes
[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
[logger_alembic]
level = INFO
handlers =
qualname = alembic
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
