"""add oauth account

Revision ID: 88cca4ba0876
Revises: 78a90a053624
Create Date: 2025-12-19 13:58:38.118756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88cca4ba0876'
down_revision: Union[str, Sequence[str], None] = '78a90a053624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_messages')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('chat_members')
    op.alter_column('member_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_member_delete_logs_id'), 'member_delete_logs', ['id'], unique=False)
    op.drop_column('member_delete_logs', 'reason')
    op.drop_constraint(op.f('uq_member_permission'), 'member_permissions', type_='unique')
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workspace_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_workspace_delete_logs_id'), 'workspace_delete_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_delete_logs_workspace_id'), 'workspace_delete_logs', ['workspace_id'], unique=False)
    op.drop_column('workspace_delete_logs', 'reason')
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('workspace_members_workspace_id_user_id_key'), 'workspace_members', type_='unique')
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(op.f('workspace_members_workspace_id_user_id_key'), 'workspace_members', ['workspace_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('workspace_delete_logs', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workspace_delete_logs_workspace_id'), table_name='workspace_delete_logs')
    op.drop_index(op.f('ix_workspace_delete_logs_id'), table_name='workspace_delete_logs')
    op.alter_column('workspace_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_member_permission'), 'member_permissions', ['workspace_member_id', 'permission_name'], postgresql_nulls_not_distinct=False)
    op.add_column('member_delete_logs', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_member_delete_logs_id'), table_name='member_delete_logs')
    op.alter_column('member_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('chat_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], name=op.f('chat_members_room_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_members_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('messages_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_rooms_pkey'),
    sa.UniqueConstraint('name', name='chat_rooms_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], name=op.f('chat_messages_room_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('chat_messages_sender_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
