"""add workspace_join_requests

Revision ID: 1e52a4a2fb12
Revises: 0a3800a8278f
Create Date: 2026-02-28 12:05:01.484098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e52a4a2fb12'
down_revision: Union[str, Sequence[str], None] = '0a3800a8278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_join_requests_id'), 'workspace_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_join_requests_status'), 'workspace_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_workspace_join_requests_user_id'), 'workspace_join_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_join_requests_workspace_id'), 'workspace_join_requests', ['workspace_id'], unique=False)



def downgrade() -> None:
    op.drop_index('ix_workspace_join_requests_workspace_id', 'workspace_join_requests')
    op.drop_index('ix_workspace_join_requests_user_id', 'workspace_join_requests')
    op.drop_index('ix_workspace_join_requests_status', 'workspace_join_requests')
    op.drop_index('ix_workspace_join_requests_id', 'workspace_join_requests')
    op.drop_table('workspace_join_requests')
    op.execute("DROP TYPE IF EXISTS joinrequeststatus")
