"""Add reset_code fields

Revision ID: 9ed8107c46e0
Revises: a0564b313f05
Create Date: 2025-12-02 03:40:14.508837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed8107c46e0'
down_revision: Union[str, Sequence[str], None] = 'a0564b313f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('reset_code', sa.String(length=6), nullable=True),
    sa.Column('reset_code_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'availability_windows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'login_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'availability_windows', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
