"""describe

Revision ID: e5a3f2e83213
Revises: d6a2ae1ee15b
Create Date: 2025-11-08 14:35:49.235506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a3f2e83213'
down_revision: Union[str, Sequence[str], None] = 'd6a2ae1ee15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
