"""create board tables

Revision ID: ed487c089d91
Revises: 2e974320f4ba
Create Date: 2026-02-05 23:22:28.708423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed487c089d91'
down_revision: Union[str, Sequence[str], None] = '2e974320f4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_board_tasks_id'), table_name='board_tasks')
    op.drop_table('board_tasks')
    op.drop_table('board_comments')
    op.create_index(op.f('ix_assessments_is_completed'), 'assessments', ['is_completed'], unique=False)
    op.create_index(op.f('ix_assessments_subject_id'), 'assessments', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('member_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_member_delete_logs_id'), 'member_delete_logs', ['id'], unique=False)
    op.drop_column('member_delete_logs', 'reason')
    op.drop_constraint(op.f('uq_member_permission'), 'member_permissions', type_='unique')
    op.alter_column('workspace_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_workspace_delete_logs_id'), 'workspace_delete_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_delete_logs_workspace_id'), 'workspace_delete_logs', ['workspace_id'], unique=False)
    op.drop_column('workspace_delete_logs', 'reason')
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('workspace_members_workspace_id_user_id_key'), 'workspace_members', type_='unique')
    op.alter_column('workspace_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('workspace_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_workspace_messages_created_at'), 'workspace_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_messages_user_id'), 'workspace_messages', ['user_id'], unique=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_workspace_messages_user_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_created_at'), table_name='workspace_messages')
    op.alter_column('workspace_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('workspace_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('workspace_members_workspace_id_user_id_key'), 'workspace_members', ['workspace_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('workspace_delete_logs', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workspace_delete_logs_workspace_id'), table_name='workspace_delete_logs')
    op.drop_index(op.f('ix_workspace_delete_logs_id'), table_name='workspace_delete_logs')
    op.alter_column('workspace_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_member_permission'), 'member_permissions', ['workspace_member_id', 'permission_name'], postgresql_nulls_not_distinct=False)
    op.add_column('member_delete_logs', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_member_delete_logs_id'), table_name='member_delete_logs')
    op.alter_column('member_delete_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_subject_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_is_completed'), table_name='assessments')
    op.create_table('board_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('board_comments_pkey'))
    )
    op.create_table('board_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attachments_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('board_tasks_assignee_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('board_tasks_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('board_tasks_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('board_tasks_pkey'))
    )
    op.create_index(op.f('ix_board_tasks_id'), 'board_tasks', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('messages_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###
